#!/usr/bin/env bash

STORED_SECRETS_PATH="$DOTFILES_PATH/${SLOTH_SECRETS_MODULE_PATH:-modules/secrets}"

if [[ -d "$STORED_SECRETS_PATH" ]]; then
  for item in $(find "$STORED_SECRETS_PATH" -maxdepth 1 -mindepth 1 -not -iname ".*" -type f -print0 | xargs -0 -I _ echo _); do
    value="$(cat "$item")"

    if [[ -z "$value" ]]; then
      value="$(dot secrets var "$(basename "$item")")"
      [[ -z "$value" ]] && continue
    fi

    export "$(basename "$item")"="$value"
  done
fi
