#!/usr/bin/env bash

STORED_SECRETS_PATH="$DOTFILES_PATH/${SLOTH_SECRETS_MODULE_PATH:-modules/secrets}"

if [[ -d "$STORED_SECRETS_PATH" ]]; then
  find "$STORED_SECRETS_PATH/vars" -path "$STORED_SECRETS_PATH/vars/.*" -prune -o -name '*' -type f -print0 | xargs -0 -I _ echo _ | while read -r item; do
    unset "$(basename "$item")"
  done
fi
