#!/usr/bin/env bash

[[ -z "$DOTLY_SECRETS_MODULE_PATH" ]] && DOTLY_SECRETS_MODULE_PATH=$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )

find "$DOTLY_SECRETS_MODULE_PATH/vars" -path "$DOTLY_SECRETS_MODULE_PATH/vars/.*" -prune -o -name '*' -type f -print | while read -r item; do
  value="$(cat $item)"
  [[ -n "$value" ]] && eval "export $(basename "$item")=\"$(cat $item)\""
  value=""
done

TODO to be deleted