#!/usr/bin/env bash

STORED_SECRETS_PATH="$DOTFILES_PATH/${DOTLY_SECRETS_MODULE_PATH:-modules/secrets}"

if [[ -d "$STORED_SECRETS_PATH" ]]; then
  find "$STORED_SECRETS_PATH/vars" -path "$STORED_SECRETS_PATH/vars/.*" -prune -o -name '*' -type f -print | while read -r item; do
    unset $(basename "$item")
  done
fi
